# **Women Cloth Reviews Prediction with Multi Nomial Naive Bayes**

# **Objective:**
To predict the sentiment (positive/negative) of women's clothing reviews using a machine learning model.

# **Data Source:**
You can use the "Women's E-Commerce Clothing Reviews" dataset from Kaggle, which includes over 23,000 reviews along with features like review text, rating, and customer recommendation.

# Import Library

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt


In [4]:
import seaborn as sns

# Import Dataset

In [9]:
from google.colab import files
uploaded = files.upload()

Saving women_Clothing_E-Commerce_Reviews.CSV to women_Clothing_E-Commerce_Reviews.CSV


In [10]:
df = pd.read_csv(r'women_Clothing_E-Commerce_Reviews.CSV')

In [11]:
df.head()

Unnamed: 0.1  Unnamed: 0  Clothing ID  Age                    Title  \
0             0           0          767   33                      NaN   
1             1           1         1080   34                      NaN   
2             2           2         1077   60  Some major design flaws   
3             3           3         1049   50         My favorite buy!   
4             4           4          847   47         Flattering shirt   

                                         Review Text  Rating  Recommended IND  \
0  Absolutely wonderful - silky and sexy and comf...       4                1   
1  Love this dress!  it's sooo pretty.  i happene...       5                1   
2  I had such high hopes for this dress and reall...       3                0   
3  I love, love, love this jumpsuit. it's fun, fl...       5                1   
4  This shirt is very flattering to all due to th...       5                1   

   Positive Feedback Count   Division Name Department Name Class Name  \
0                        0       Initmates        Intimate  Intimates   
1                        4         General         Dresses    Dresses   
2                        0         General         Dresses    Dresses   
3                        0  General Petite         Bottoms      Pants   
4                        6         General            Tops    Blouses   

                                      Review Text DE  
0    Absolut wundervoll - seidig und sexy und bequem  
1  Liebe dieses Kleid! es ist sooo hübsch. Ich fa...  
2  Ich hatte so große Hoffnungen auf dieses Kleid...  
3  Ich liebe, liebe, liebe diesen Overall. Es mac...  
4  Dieses Shirt ist aufgrund der verstellbaren Fr...

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Unnamed: 0.1             23486 non-null  int64 
 1   Unnamed: 0               23486 non-null  int64 
 2   Clothing ID              23486 non-null  int64 
 3   Age                      23486 non-null  int64 
 4   Title                    19676 non-null  object
 5   Review Text              22641 non-null  object
 6   Rating                   23486 non-null  int64 
 7   Recommended IND          23486 non-null  int64 
 8   Positive Feedback Count  23486 non-null  int64 
 9   Division Name            23472 non-null  object
 10  Department Name          23472 non-null  object
 11  Class Name               23472 non-null  object
 12  Review Text DE           22641 non-null  object
dtypes: int64(7), object(6)
memory usage: 2.3+ MB


In [14]:
df.shape

(23486, 13)

# Missing Values

Remove missing values in Reviews columns with No Review text.

In [15]:
df.isna().sum()

Unnamed: 0.1                  0
Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                 845
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
Review Text DE              845
dtype: int64

In [16]:
df[df['Review Text']==""]=np.NaN

In [17]:
df['Review Text'].fillna("No Review",inplace=True)

<ipython-input-17-635aafcfac6c>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Review Text'].fillna("No Review",inplace=True)


In [18]:
df.isna().sum()

Unnamed: 0.1                  0
Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                   0
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
Review Text DE              845
dtype: int64

In [20]:
print(df.columns)


Index(['Unnamed: 0.1', 'Unnamed: 0', 'Clothing ID', 'Age', 'Title',
       'Review Text', 'Rating', 'Recommended IND', 'Positive Feedback Count',
       'Division Name', 'Department Name', 'Class Name', 'Review Text DE'],
      dtype='object')


In [21]:
df['Review Text']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review Text, Length: 23486, dtype: object

# Define Target(Y) and Feature(X)

In [22]:
df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'Clothing ID', 'Age', 'Title',
       'Review Text', 'Rating', 'Recommended IND', 'Positive Feedback Count',
       'Division Name', 'Department Name', 'Class Name', 'Review Text DE'],
      dtype='object')

In [23]:
x=df['Review Text']

In [24]:
y=df['Rating']

In [25]:
df['Rating'].value_counts()

Rating
5    13131
4     5077
3     2871
2     1565
1      842
Name: count, dtype: int64

# Train Test Split

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7, stratify=y,random_state=2529)

In [28]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((16440,), (7046,), (16440,), (7046,))

# Get Feature Text Conversion to Tokens

In [29]:
from sklearn.feature_extraction.text import CountVectorizer

In [30]:
cv=CountVectorizer(lowercase = True, analyzer='word',ngram_range=(2,3),stop_words='english' , max_features=5000)

In [31]:
x_train=cv.fit_transform(x_train)

In [32]:
cv.get_feature_names_out()

array(['10 12', '10 bought', '10 fit', ..., 'yellow color', 'yoga pants',
       'zipper little'], dtype=object)

In [33]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [34]:
x_test = cv.fit_transform(x_test)

In [36]:
cv.get_feature_names_out()

array(['10 12', '10 dress', '10 fit', ..., 'years come', 'years old',
       'yoga pants'], dtype=object)

In [37]:
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

# Get MOdel Train

In [38]:
from sklearn.naive_bayes import MultinomialNB

In [39]:
model=MultinomialNB()

In [41]:
model.fit(x_train,y_train)

MultinomialNB()

# Get Model Prediction

In [42]:
y_pred=model.predict(x_test)

In [43]:
y_pred.shape

(7046,)

In [44]:
y_pred

array([1, 5, 5, ..., 5, 5, 5])

# Get Probability of Each Predicted Class

In [45]:
model.predict_proba(x_test)

array([[0.71118473, 0.02625165, 0.15465118, 0.01496876, 0.09294369],
       [0.02416867, 0.04769471, 0.35268622, 0.16185007, 0.41360034],
       [0.03582725, 0.06660584, 0.12226277, 0.21618005, 0.55912409],
       ...,
       [0.02320281, 0.08950939, 0.08962183, 0.16719203, 0.63047394],
       [0.01167675, 0.00202714, 0.08539004, 0.34347398, 0.55743209],
       [0.03959824, 0.05612822, 0.00688869, 0.1560574 , 0.74132745]])

# Get Model Evalution

In [46]:
from sklearn.metrics import confusion_matrix,classification_report

In [47]:
print(confusion_matrix(y_test,y_pred))

[[  15   13   45   36  144]
 [  43   43   86   85  213]
 [ 116   78  113  166  388]
 [ 166  108  194  336  719]
 [ 371  272  349  722 2225]]


In [48]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.02      0.06      0.03       253
           2       0.08      0.09      0.09       470
           3       0.14      0.13      0.14       861
           4       0.25      0.22      0.23      1523
           5       0.60      0.56      0.58      3939

    accuracy                           0.39      7046
   macro avg       0.22      0.21      0.21      7046
weighted avg       0.42      0.39      0.40      7046



# Recategories Ratings as Poor (0) and Good (1)

In [49]:
df['Rating'].value_counts()

Rating
5    13131
4     5077
3     2871
2     1565
1      842
Name: count, dtype: int64

Re-Rating as 1,2,3 as 0 and 4,5 as 1

In [50]:
df.replace({'Rating':{1:0,2:0,3:0,4:1,5:1}},inplace=True)

In [51]:
y=df['Rating']

# Train Test Split

In [52]:
from sklearn.model_selection import train_test_split

In [53]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7,stratify=y,random_state=2529)

In [54]:
x_train.shape, x_test.shape,y_train.shape,y_test.shape

((16440,), (7046,), (16440,), (7046,))

# Get Feature Text Conversion to Tokens

In [55]:
from sklearn.feature_extraction.text import CountVectorizer

In [56]:
cv= CountVectorizer(lowercase=True, analyzer='word', ngram_range=(2,3), stop_words='english', max_features=5000)

In [57]:
x_train=cv.fit_transform(x_train)

In [58]:
x_test=cv.fit_transform(x_test)

# Get Model Re-train

In [60]:
from sklearn.naive_bayes import MultinomialNB

In [61]:
model=MultinomialNB()

In [62]:
model.fit(x_train,y_train)

MultinomialNB()

# Get Model Prediction

In [63]:
y_pred=model.predict(x_test)

In [65]:
y_pred.shape

(7046,)

In [66]:
y_pred

array([1, 1, 1, ..., 1, 1, 1])

## Get Model Evalution

In [67]:
from sklearn.metrics import confusion_matrix,classification_report

In [68]:
print(confusion_matrix(y_test,y_pred))

[[ 449 1134]
 [ 989 4474]]


In [69]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.31      0.28      0.30      1583
           1       0.80      0.82      0.81      5463

    accuracy                           0.70      7046
   macro avg       0.56      0.55      0.55      7046
weighted avg       0.69      0.70      0.69      7046



# Explaination

In this project, I aimed to predict the sentiment (positive or negative) of women's clothing reviews using the Multinomial Naive Bayes algorithm. I used the "Women's E-Commerce Clothing Reviews" dataset, focusing on the review text as the feature and ratings as the target. The ratings were re-categorized: ratings 1, 2, 3 as negative (0), and 4, 5 as positive (1). After splitting the data into training and testing sets, I applied CountVectorizer to tokenize the review text and trained the Naive Bayes model. The model achieved a 70% accuracy, performing better on positive reviews than on negative ones.